var searchData=
[
  ['unbounded_5fmessage_5fblock_0',['unbounded_message_block',['../classdiscord__core__api_1_1unbounded__message__block.html',1,'discord_core_api']]],
  ['unbounded_5fmessage_5fblock_3c_20discord_5fcore_5fapi_3a_3aaudio_5fframe_5fdata_20_3e_1',['unbounded_message_block&lt; discord_core_api::audio_frame_data &gt;',['../classdiscord__core__api_1_1unbounded__message__block.html',1,'discord_core_api']]],
  ['unbounded_5fmessage_5fblock_3c_20discord_5fcore_5fapi_3a_3ainteraction_5fdata_20_3e_2',['unbounded_message_block&lt; discord_core_api::interaction_data &gt;',['../classdiscord__core__api_1_1unbounded__message__block.html',1,'discord_core_api']]],
  ['unbounded_5fmessage_5fblock_3c_20discord_5fcore_5finternal_3a_3avoice_5fconnection_5fdata_20_3e_3',['unbounded_message_block&lt; discord_core_internal::voice_connection_data &gt;',['../classdiscord__core__api_1_1unbounded__message__block.html',1,'discord_core_api']]],
  ['unbounded_5fmessage_5fblock_3c_20std_3a_3acoroutine_5fhandle_3c_3e_20_3e_4',['unbounded_message_block&lt; std::coroutine_handle&lt;&gt; &gt;',['../classdiscord__core__api_1_1unbounded__message__block.html',1,'discord_core_api']]],
  ['unbounded_5fmessage_5fblock_3c_20value_5ftype_20_3e_5',['unbounded_message_block&lt; value_type &gt;',['../classdiscord__core__api_1_1unbounded__message__block.html',1,'discord_core_api']]],
  ['unicode_5femoji_6',['unicode_emoji',['../structdiscord__core__api_1_1unicode__emoji.html',1,'discord_core_api']]],
  ['unique_5fptr_7',['unique_ptr',['../classdiscord__core__api_1_1unique__ptr.html',1,'discord_core_api']]],
  ['unique_5fptr_3c_20discord_5fcore_5fapi_3a_3adiscord_5fcore_5fclient_20_3e_8',['unique_ptr&lt; discord_core_api::discord_core_client &gt;',['../classdiscord__core__api_1_1unique__ptr.html',1,'discord_core_api']]],
  ['unique_5fptr_3c_20discord_5fcore_5fapi_3a_3adiscord_5fcore_5finternal_3a_3ahttps_5fclient_20_3e_9',['unique_ptr&lt; discord_core_api::discord_core_internal::https_client &gt;',['../classdiscord__core__api_1_1unique__ptr.html',1,'discord_core_api']]],
  ['unique_5fptr_3c_20discord_5fcore_5fapi_3a_3ainput_5fevent_5fdata_20_3e_10',['unique_ptr&lt; discord_core_api::input_event_data &gt;',['../classdiscord__core__api_1_1unique__ptr.html',1,'discord_core_api']]],
  ['unique_5fptr_3c_20discord_5fcore_5fapi_3a_3ainteraction_5fdata_20_3e_11',['unique_ptr&lt; discord_core_api::interaction_data &gt;',['../classdiscord__core__api_1_1unique__ptr.html',1,'discord_core_api']]],
  ['unique_5fptr_3c_20opusdecoder_2c_20discord_5fcore_5fapi_3a_3adiscord_5fcore_5finternal_3a_3aopus_5fdecoder_5fwrapper_3a_3aopus_5fdecoder_5fdeleter_20_3e_12',['unique_ptr&lt; OpusDecoder, discord_core_api::discord_core_internal::opus_decoder_wrapper::opus_decoder_deleter &gt;',['../classdiscord__core__api_1_1unique__ptr.html',1,'discord_core_api']]],
  ['unique_5fptr_3c_20opusencoder_2c_20discord_5fcore_5fapi_3a_3adiscord_5fcore_5finternal_3a_3aopus_5fencoder_5fwrapper_3a_3aopus_5fencoder_5fdeleter_20_3e_13',['unique_ptr&lt; OpusEncoder, discord_core_api::discord_core_internal::opus_encoder_wrapper::opus_encoder_deleter &gt;',['../classdiscord__core__api_1_1unique__ptr.html',1,'discord_core_api']]],
  ['unique_5fptr_3c_20return_5ftype_20_3e_14',['unique_ptr&lt; return_type &gt;',['../classdiscord__core__api_1_1unique__ptr.html',1,'discord_core_api']]],
  ['unique_5fptr_3c_20socket_2c_20socket_5fdeleter_20_3e_15',['unique_ptr&lt; SOCKET, socket_deleter &gt;',['../classdiscord__core__api_1_1unique__ptr.html',1,'discord_core_api']]],
  ['unique_5fptr_3c_20ssl_2c_20ssl_5fdeleter_20_3e_16',['unique_ptr&lt; SSL, ssl_deleter &gt;',['../classdiscord__core__api_1_1unique__ptr.html',1,'discord_core_api']]],
  ['unique_5fptr_3c_20ssl_5fctx_2c_20ssl_5fctx_5fdeleter_20_3e_17',['unique_ptr&lt; SSL_CTX, ssl_ctx_deleter &gt;',['../classdiscord__core__api_1_1unique__ptr.html',1,'discord_core_api']]],
  ['unique_5fptr_3c_20std_3a_3aexception_5fptr_20_3e_18',['unique_ptr&lt; std::exception_ptr &gt;',['../classdiscord__core__api_1_1unique__ptr.html',1,'discord_core_api']]],
  ['unique_5fptr_3c_20value_5ftype_5b_5d_2c_20deleter_20_3e_19',['unique_ptr&lt; value_type[], deleter &gt;',['../classdiscord__core__api_1_1unique__ptr.html',1,'discord_core_api']]],
  ['unique_5fptr_3c_20voice_5fconnection_5fbridge_20_3e_20',['unique_ptr&lt; voice_connection_bridge &gt;',['../classdiscord__core__api_1_1unique__ptr.html',1,'discord_core_api']]],
  ['unique_5fptr_3c_20void_20_3e_21',['unique_ptr&lt; void &gt;',['../classdiscord__core__api_1_1unique__ptr.html',1,'discord_core_api']]],
  ['unpin_5fmessage_5fdata_22',['unpin_message_data',['../structdiscord__core__api_1_1unpin__message__data.html',1,'discord_core_api']]],
  ['update_5fchannel_5fdata_23',['update_channel_data',['../structdiscord__core__api_1_1update__channel__data.html',1,'discord_core_api']]],
  ['update_5fpresence_5fdata_24',['update_presence_data',['../structdiscord__core__api_1_1update__presence__data.html',1,'discord_core_api']]],
  ['update_5fvoice_5fstate_5fdata_25',['update_voice_state_data',['../structdiscord__core__api_1_1update__voice__state__data.html',1,'discord_core_api']]],
  ['update_5fvoice_5fstate_5fdata_5fdc_26',['update_voice_state_data_dc',['../structdiscord__core__api_1_1update__voice__state__data__dc.html',1,'discord_core_api']]],
  ['user_5fcache_5fdata_27',['user_cache_data',['../classdiscord__core__api_1_1user__cache__data.html',1,'discord_core_api']]],
  ['user_5fdata_28',['user_data',['../classdiscord__core__api_1_1user__data.html',1,'discord_core_api']]],
  ['users_29',['users',['../classdiscord__core__api_1_1users.html',1,'discord_core_api']]]
];
