var searchData=
[
  ['reaction_5fdata_0',['reaction_data',['../classdiscord__core__api_1_1reaction__data.html',1,'discord_core_api']]],
  ['reaction_5fremove_5fdata_1',['reaction_remove_data',['../structdiscord__core__api_1_1reaction__remove__data.html',1,'discord_core_api']]],
  ['reactions_2',['reactions',['../classdiscord__core__api_1_1reactions.html',1,'discord_core_api']]],
  ['remove_5fguild_5fban_5fdata_3',['remove_guild_ban_data',['../structdiscord__core__api_1_1remove__guild__ban__data.html',1,'discord_core_api']]],
  ['remove_5fguild_5fmember_5fdata_4',['remove_guild_member_data',['../structdiscord__core__api_1_1remove__guild__member__data.html',1,'discord_core_api']]],
  ['remove_5fguild_5fmember_5frole_5fdata_5',['remove_guild_member_role_data',['../structdiscord__core__api_1_1remove__guild__member__role__data.html',1,'discord_core_api']]],
  ['remove_5fguild_5frole_5fdata_6',['remove_guild_role_data',['../structdiscord__core__api_1_1remove__guild__role__data.html',1,'discord_core_api']]],
  ['remove_5frecipient_5ffrom_5fgroup_5fdmdata_7',['remove_recipient_from_group_dmdata',['../structdiscord__core__api_1_1remove__recipient__from__group__dmdata.html',1,'discord_core_api']]],
  ['remove_5fthread_5fmember_5fdata_8',['remove_thread_member_data',['../structdiscord__core__api_1_1remove__thread__member__data.html',1,'discord_core_api']]],
  ['repeated_5ffunction_5fdata_9',['repeated_function_data',['../structdiscord__core__api_1_1repeated__function__data.html',1,'discord_core_api']]],
  ['resolved_5fdata_10',['resolved_data',['../structdiscord__core__api_1_1resolved__data.html',1,'discord_core_api']]],
  ['respond_5fto_5finput_5fevent_5fdata_11',['respond_to_input_event_data',['../classdiscord__core__api_1_1respond__to__input__event__data.html',1,'discord_core_api']]],
  ['ring_5fbuffer_12',['ring_buffer',['../classdiscord__core__api_1_1discord__core__internal_1_1ring__buffer.html',1,'discord_core_api::discord_core_internal']]],
  ['ring_5fbuffer_3c_20uint8_5ft_2c_2010_20_3e_13',['ring_buffer&lt; uint8_t, 10 &gt;',['../classdiscord__core__api_1_1discord__core__internal_1_1ring__buffer.html',1,'discord_core_api::discord_core_internal']]],
  ['ring_5fbuffer_3c_20uint8_5ft_2c_2016_20_3e_14',['ring_buffer&lt; uint8_t, 16 &gt;',['../classdiscord__core__api_1_1discord__core__internal_1_1ring__buffer.html',1,'discord_core_api::discord_core_internal']]],
  ['ring_5fbuffer_3c_20uint8_5ft_2c_2064_20_3e_15',['ring_buffer&lt; uint8_t, 64 &gt;',['../classdiscord__core__api_1_1discord__core__internal_1_1ring__buffer.html',1,'discord_core_api::discord_core_internal']]],
  ['ring_5fbuffer_5finterface_16',['ring_buffer_interface',['../classdiscord__core__api_1_1discord__core__internal_1_1ring__buffer__interface.html',1,'discord_core_api::discord_core_internal']]],
  ['ring_5fbuffer_5finterface_3c_20ring_5fbuffer_5finterface_3c_20jsonifier_5finternal_3a_3aunwrap_5ft_3c_20uint8_5ft_20_3e_2c_201024_20_2a16_20_3e_2c_20slice_5fcount_20_3e_17',['ring_buffer_interface&lt; ring_buffer_interface&lt; jsonifier_internal::unwrap_t&lt; uint8_t &gt;, 1024 *16 &gt;, slice_count &gt;',['../classdiscord__core__api_1_1discord__core__internal_1_1ring__buffer__interface.html',1,'discord_core_api::discord_core_internal']]],
  ['ring_5fbuffer_5finterface_3c_20ring_5fbuffer_5finterface_3c_20jsonifier_5finternal_3a_3aunwrap_5ft_3c_20value_5ftype_5fnew_20_3e_2c_201024_20_2a16_20_3e_2c_20slice_5fcount_20_3e_18',['ring_buffer_interface&lt; ring_buffer_interface&lt; jsonifier_internal::unwrap_t&lt; value_type_new &gt;, 1024 *16 &gt;, slice_count &gt;',['../classdiscord__core__api_1_1discord__core__internal_1_1ring__buffer__interface.html',1,'discord_core_api::discord_core_internal']]],
  ['role_5fcache_5fdata_19',['role_cache_data',['../classdiscord__core__api_1_1role__cache__data.html',1,'discord_core_api']]],
  ['role_5fdata_20',['role_data',['../classdiscord__core__api_1_1role__data.html',1,'discord_core_api']]],
  ['role_5fposition_5fdata_21',['role_position_data',['../structdiscord__core__api_1_1role__position__data.html',1,'discord_core_api']]],
  ['role_5ftags_5fdata_22',['role_tags_data',['../structdiscord__core__api_1_1role__tags__data.html',1,'discord_core_api']]],
  ['roles_23',['roles',['../classdiscord__core__api_1_1roles.html',1,'discord_core_api']]]
];
