var searchData=
[
  ['rawframedata_0',['RawFrameData',['../d7/d75/a02805.html',1,'DiscordCoreAPI']]],
  ['reaction_1',['Reaction',['../d0/d9d/a03289.html',1,'DiscordCoreAPI']]],
  ['reactiondata_2',['ReactionData',['../d9/d9d/a02425.html',1,'DiscordCoreAPI']]],
  ['reactionremovedata_3',['ReactionRemoveData',['../d0/dce/a02617.html',1,'DiscordCoreAPI']]],
  ['reactions_4',['Reactions',['../da/d0a/a03297.html',1,'DiscordCoreAPI']]],
  ['removeguildbandata_5',['RemoveGuildBanData',['../d1/dc2/a02877.html',1,'DiscordCoreAPI']]],
  ['removeguildmemberdata_6',['RemoveGuildMemberData',['../dd/dfd/a03017.html',1,'DiscordCoreAPI']]],
  ['removeguildmemberroledata_7',['RemoveGuildMemberRoleData',['../d3/d34/a03305.html',1,'DiscordCoreAPI']]],
  ['removeguildroledata_8',['RemoveGuildRoleData',['../d8/d5d/a03329.html',1,'DiscordCoreAPI']]],
  ['removerecipientfromgroupdmdata_9',['RemoveRecipientFromGroupDMData',['../de/d5d/a03565.html',1,'DiscordCoreAPI']]],
  ['removethreadmemberdata_10',['RemoveThreadMemberData',['../d8/dbb/a03501.html',1,'DiscordCoreAPI']]],
  ['repeatedfunctiondata_11',['RepeatedFunctionData',['../d8/d13/a03609.html',1,'DiscordCoreAPI']]],
  ['resolveddata_12',['ResolvedData',['../df/d50/a02725.html',1,'DiscordCoreAPI']]],
  ['respondtoinputeventdata_13',['RespondToInputEventData',['../da/d7d/a02785.html',1,'DiscordCoreAPI']]],
  ['role_14',['Role',['../d3/d55/a03341.html',1,'DiscordCoreAPI']]],
  ['roledata_15',['RoleData',['../d7/d1a/a02381.html',1,'DiscordCoreAPI']]],
  ['rolepositiondata_16',['RolePositionData',['../d8/ddd/a03317.html',1,'DiscordCoreAPI']]],
  ['roles_17',['Roles',['../d6/df3/a03349.html',1,'DiscordCoreAPI']]],
  ['roletagsdata_18',['RoleTagsData',['../de/d4e/a02289.html',1,'DiscordCoreAPI']]]
];
