var _audio_decoder_8hpp =
[
    [ "discord_core_api::discord_core_internal::opus_decoder_wrapper::opus_decoder_deleter", "structdiscord__core__api_1_1discord__core__internal_1_1opus__decoder__wrapper_1_1opus__decoder__deleter.html", "structdiscord__core__api_1_1discord__core__internal_1_1opus__decoder__wrapper_1_1opus__decoder__deleter" ]
];