var _audio_encoder_8hpp =
[
    [ "discord_core_api::discord_core_internal::opus_encoder_wrapper::opus_encoder_deleter", "structdiscord__core__api_1_1discord__core__internal_1_1opus__encoder__wrapper_1_1opus__encoder__deleter.html", "structdiscord__core__api_1_1discord__core__internal_1_1opus__encoder__wrapper_1_1opus__encoder__deleter" ]
];