var dir_9b16bdde4f6a21e020962bfdb0aa5092 =
[
    [ "Utilities", "dir_e0f040a3b822072bd11eaa52f82ed328.html", "dir_e0f040a3b822072bd11eaa52f82ed328" ],
    [ "ApplicationCommandEntities.hpp", "_application_command_entities_8hpp.html", null ],
    [ "AutoModerationEntities.hpp", "_auto_moderation_entities_8hpp.html", null ],
    [ "ChannelEntities.hpp", "_channel_entities_8hpp.html", null ],
    [ "CommandController.hpp", "_command_controller_8hpp.html", "_command_controller_8hpp" ],
    [ "CoRoutine.hpp", "_co_routine_8hpp.html", "_co_routine_8hpp" ],
    [ "DiscordCoreClient.hpp", "_discord_core_client_8hpp.html", null ],
    [ "EventManager.hpp", "_event_manager_8hpp.html", null ],
    [ "FoundationEntities.hpp", "_foundation_entities_8hpp.html", "_foundation_entities_8hpp" ],
    [ "GuildEntities.hpp", "_guild_entities_8hpp.html", null ],
    [ "GuildMemberEntities.hpp", "_guild_member_entities_8hpp.html", null ],
    [ "GuildScheduledEventEntities.hpp", "_guild_scheduled_event_entities_8hpp.html", null ],
    [ "Index.hpp", "_index_8hpp.html", null ],
    [ "InputEvents.hpp", "_input_events_8hpp.html", null ],
    [ "InteractionEntities.hpp", "_interaction_entities_8hpp.html", null ],
    [ "JsonSpecializations.hpp", "_json_specializations_8hpp.html", null ],
    [ "MessageEntities.hpp", "_message_entities_8hpp.html", "_message_entities_8hpp" ],
    [ "ReactionEntities.hpp", "_reaction_entities_8hpp.html", null ],
    [ "RoleEntities.hpp", "_role_entities_8hpp.html", null ],
    [ "SongAPI.hpp", "_song_a_p_i_8hpp.html", null ],
    [ "SoundCloudAPI.hpp", "_sound_cloud_a_p_i_8hpp.html", null ],
    [ "StageInstanceEntities.hpp", "_stage_instance_entities_8hpp.html", "_stage_instance_entities_8hpp" ],
    [ "StickerEntities.hpp", "_sticker_entities_8hpp.html", null ],
    [ "ThreadEntities.hpp", "_thread_entities_8hpp.html", null ],
    [ "ToEntity.hpp", "_to_entity_8hpp.html", null ],
    [ "UserEntities.hpp", "_user_entities_8hpp.html", null ],
    [ "Utilities.hpp", "_utilities_8hpp.html", "_utilities_8hpp" ],
    [ "VoiceConnection.hpp", "_voice_connection_8hpp.html", "_voice_connection_8hpp" ],
    [ "WebHookEntities.hpp", "_web_hook_entities_8hpp.html", null ],
    [ "YouTubeAPI.hpp", "_you_tube_a_p_i_8hpp.html", null ]
];