var dir_74389ed8173ad57b461b9d623a1f3867 =
[
    [ "ApplicationCommandEntities.cpp", "_application_command_entities_8cpp.html", null ],
    [ "AutoModerationEntities.cpp", "_auto_moderation_entities_8cpp.html", null ],
    [ "ChannelEntities.cpp", "_channel_entities_8cpp.html", null ],
    [ "CommandController.cpp", "_command_controller_8cpp.html", null ],
    [ "DiscordCoreClient.cpp", "_discord_core_client_8cpp.html", null ],
    [ "DllMain.cpp", "_dll_main_8cpp.html", null ],
    [ "EventManager.cpp", "_event_manager_8cpp.html", null ],
    [ "FoundationEntities.cpp", "_foundation_entities_8cpp.html", null ],
    [ "GuildEntities.cpp", "_guild_entities_8cpp.html", null ],
    [ "GuildMemberEntities.cpp", "_guild_member_entities_8cpp.html", null ],
    [ "GuildScheduledEventEntities.cpp", "_guild_scheduled_event_entities_8cpp.html", null ],
    [ "HttpsClient.cpp", "_https_client_8cpp.html", null ],
    [ "InputEvents.cpp", "_input_events_8cpp.html", null ],
    [ "InteractionEntities.cpp", "_interaction_entities_8cpp.html", null ],
    [ "MessageEntities.cpp", "_message_entities_8cpp.html", null ],
    [ "ReactionEntities.cpp", "_reaction_entities_8cpp.html", null ],
    [ "RoleEntities.cpp", "_role_entities_8cpp.html", null ],
    [ "SongAPI.cpp", "_song_a_p_i_8cpp.html", null ],
    [ "SoundCloudAPI.cpp", "_sound_cloud_a_p_i_8cpp.html", null ],
    [ "StageInstanceEntities.cpp", "_stage_instance_entities_8cpp.html", null ],
    [ "StickerEntities.cpp", "_sticker_entities_8cpp.html", null ],
    [ "ThreadEntities.cpp", "_thread_entities_8cpp.html", null ],
    [ "UserEntities.cpp", "_user_entities_8cpp.html", null ],
    [ "Utilities.cpp", "_utilities_8cpp.html", "_utilities_8cpp" ],
    [ "VoiceConnection.cpp", "_voice_connection_8cpp.html", null ],
    [ "WebHookEntities.cpp", "_web_hook_entities_8cpp.html", null ],
    [ "WebSocketClient.cpp", "_web_socket_client_8cpp.html", null ],
    [ "YouTubeAPI.cpp", "_you_tube_a_p_i_8cpp.html", null ]
];