var documentation_examples =
[
    [ "Login/Setup", "login_setup.html", "login_setup" ],
    [ "General Usage", "general_usage.html", "general_usage" ],
    [ "Autocompletes", "auto_completes.html", "auto_completes" ],
    [ "Buttons", "buttons.html", "buttons" ],
    [ "Select Menus", "select_menus.html", "select_menus" ],
    [ "Modals", "modals.html", "modals" ],
    [ "Voice Connections", "voice_connections.html", "voice_connections" ],
    [ "Application-Commands", "application_commands.html", "application_commands" ],
    [ "Auto-Moderation-Rules", "auto_moderation_rules.html", "auto_moderation_rules" ],
    [ "Channels", "channels.html", "channels" ],
    [ "Guilds", "guilds.html", "guilds" ],
    [ "Guild-Members", "guild_members.html", "guild_members" ],
    [ "Guild Scheduled Events", "guild_scheduled_events.html", "guild_scheduled_events" ],
    [ "Input Events", "input_events.html", "input_events" ],
    [ "Interactions", "interactions.html", "interactions" ],
    [ "Messages", "messages.html", "messages" ],
    [ "Reactions", "reactions.html", "reactions" ],
    [ "Roles", "roles.html", "roles" ],
    [ "Stage-Instances", "stage_instances.html", "stage_instances" ],
    [ "Stickers", "stickers.html", "stickers" ],
    [ "Threads", "threads.html", "threads" ],
    [ "Users", "users.html", "users" ],
    [ "Webhooks", "webhooks.html", "webhooks" ]
];