var guilds =
[
    [ "Getting Audit Logs", "getting_audit_logs.html", null ],
    [ "Creating a Guild", "creating_a_guild.html", null ],
    [ "Getting All Guilds", "getting_all_guilds.html", null ],
    [ "Getting a Guild", "getting_a_guild.html", null ],
    [ "Getting a Guild Preview", "getting_a_guild_preview.html", null ],
    [ "Modifying a Guild", "modifying_a_guild.html", null ],
    [ "Deleting a Guild", "deleting_a_guild.html", null ],
    [ "Getting Guild Bans", "getting_guild_bans.html", null ],
    [ "Getting a Guild Ban", "getting_a_guild_ban.html", null ],
    [ "Creating a Guild Ban", "creating_a_guild_ban.html", null ],
    [ "Removing a Guild Ban", "removing_a_guild_ban.html", null ],
    [ "Getting a Guild Prune Count", "getting_a_guild_prune_count.html", null ],
    [ "Beginning a Guild Prune", "beginning_a_guild_prune.html", null ],
    [ "Getting Guild Voice Regions", "getting_guild_voice_regions.html", null ],
    [ "Getting Guild Invites", "getting_guild_invites.html", null ],
    [ "Getting Guild Integrations", "getting_guild_integrations.html", null ],
    [ "Deleting a Guild Integration", "deleting_a_guild_integration.html", null ],
    [ "Getting Guild Widget Settings", "getting_guild_widget_settings.html", null ],
    [ "Modifying a Guild Widget", "modifying_a_guild_widget.html", null ],
    [ "Getting a Guild Widget", "getting_a_guild_widget.html", null ],
    [ "Getting a Guild Vanity Invite", "getting_a_guild_vanity_invite.html", null ],
    [ "Getting a Guild Widget Image", "getting_a_guild_widget_image.html", null ],
    [ "Getting a Guild Welcome Screen", "getting_a_guild_welcome_screen.html", null ],
    [ "Modifying a Guild Welcome Screen", "modifying_a_guild_welcome_screen.html", null ],
    [ "Getting a Guild Template", "getting_a_guild_template.html", null ],
    [ "Creating a Guild From a Guild Template", "creating_a_guild_from_a_guild_template.html", null ],
    [ "Getting Guild Templates", "getting_guild_templates.html", null ],
    [ "Creating a Guild Template", "creating_a_guild_template.html", null ],
    [ "Syncing a Guild Template", "syncing_a_guild_template.html", null ],
    [ "Modifying a Guild Template", "modifying_a_guild_template.html", null ],
    [ "Deleting a Guild Template", "deleting_a_guild_template.html", null ],
    [ "Getting an Invite", "getting_an_invite.html", null ],
    [ "Getting Current User's Guilds", "getting_current_users_guilds.html", null ],
    [ "Leaving a Guild", "leaving_a_guild.html", null ]
];