name: Upload Documentation.
on:
  push:

jobs:
   Upload-It:
    runs-on: ubuntu-22.04

    steps:
         - name: Store the public SSH key, and copy it. 
           run: |
                echo -e "${{ secrets.AWS_KEY }}" >> aws_key.pem
                sudo cp ./aws_key.pem /root/.ssh/id_rsa.pem
                sudo chmod 600 /root/.ssh/id_rsa.pem
                
         - name: Clone the data over to the web server.
           run: sudo ssh -i /root/.ssh/id_rsa.pem -o StrictHostKeyChecking=no ubuntu@ec2-3-144-188-157.us-east-2.compute.amazonaws.com 
               "cd /var/www && sudo rm -rf discordcoreapi && sudo git clone https://github.com/RealTimeChris/DiscordCoreAPI-Docs --depth=1 ./discordcoreapi"

